projectGroup=org.springaicommunity
projectVersion=0.1.0-SNAPSHOT
projectUrl=https://github.com/JHPrk/spring-ai-mcp-sigv4
scmConnection=scm:git:https://github.com/JHPrk/spring-ai-mcp-sigv4.git
scmDeveloperConnection=scm:git:ssh://git@github.com/JHPrk/spring-ai-mcp-sigv4.git
developerId=JHPrk
developerName=Jaehyeon Park

org.gradle.caching=true
org.gradle.parallel=true
